
services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend/react-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start



  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./src/backend:/app
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    depends_on:
      - frontend

volumes:
  db_data:
